/**
 * shared/types.ts
 *
 * Central type definitions for the entire workshop.
 *
 * WHY A SHARED TYPES FILE?
 * Every module in this workshop (schema, loop, orchestrator, persistence)
 * exchanges the same core objects. Defining them once here means:
 *   1. Participants see the full data model up front.
 *   2. There's no "which version of ToolCall am I importing?" confusion.
 *   3. It mirrors how real production code is structured.
 *
 * These types follow the OpenAI Chat Completions tool-calling format,
 * which has become the de-facto standard adopted by Anthropic, Mistral,
 * Cohere, and most open-source model servers.
 */

// ---------------------------------------------------------------------------
// SECTION 1: TOOL DEFINITION
// What you send to the LLM to tell it what tools exist.
// ---------------------------------------------------------------------------

/**
 * A JSON Schema object that describes a single property in a tool's parameter list.
 *
 * The LLM reads this schema and generates valid arguments — so the more precise
 * your schema, the fewer hallucinated / malformed arguments you get.
 */
export interface JSONSchemaProperty {
  /** Primitive type. Use "string" | "number" | "boolean" | "array" | "object". */
  type: "string" | "number" | "boolean" | "array" | "object" | "null";

  /** Human-readable explanation. The LLM uses this to decide WHEN to pass this argument. */
  description?: string;

  /** For "string" type: restrict to a fixed set of allowed values (acts like an enum). */
  enum?: string[];

  /** For "array" type: describes the type of each element in the array. */
  items?: JSONSchemaProperty;

  /** For "object" type: describes each named field inside the object. */
  properties?: Record<string, JSONSchemaProperty>;

  /** For "object" type: which fields are mandatory. */
  required?: string[];
}

/**
 * The parameters block of a tool definition.
 * Always type: "object" at the top level — the LLM will fill in each property.
 */
export interface ToolParameters {
  type: "object";
  properties: Record<string, JSONSchemaProperty>;
  /** List of property names the LLM MUST provide (omit optional ones here). */
  required?: string[];
}

/**
 * A complete tool definition — this is what you put in the `tools` array
 * when calling the OpenAI Chat Completions API.
 *
 * Structure:
 *   tools: [{ type: "function", function: ToolFunction }]
 */
export interface ToolFunction {
  /** The name the LLM will use to call this tool. Use snake_case. */
  name: string;

  /**
   * Critical description: explain WHEN and WHY to use this tool.
   * Bad:  "Gets weather"
   * Good: "Fetches current weather conditions for a city. Use this when
   *        the user asks about temperature, forecast, or weather conditions."
   */
  description: string;

  /** JSON Schema describing the arguments the LLM must supply. */
  parameters: ToolParameters;
}

/**
 * The wrapper the OpenAI API expects around a ToolFunction.
 * Anthropic, Mistral etc. skip this wrapper — they take ToolFunction directly.
 */
export interface ToolDefinition {
  type: "function";
  function: ToolFunction;
}

// ---------------------------------------------------------------------------
// SECTION 2: TOOL CALLS (LLM OUTPUT)
// What the LLM sends back when it decides to use a tool.
// ---------------------------------------------------------------------------

/**
 * A single tool call issued by the LLM inside an assistant message.
 *
 * The LLM may request MULTIPLE tool calls in one response (parallel calling).
 * Always process all of them before sending results back.
 */
export interface ToolCall {
  /**
   * Unique ID generated by the LLM for this specific call. refer to callLLM function
   * in reasoning-loop.ts
   * You MUST echo this back in the tool result — it's how the LLM matches
   * results to calls when multiple tools ran in parallel.
   */
  id: string;

  /** Always "function" for function-based tools. */
  type: "function";

  function: {
    /** Name of the tool the LLM wants to invoke. */
    name: string;

    /**
     * JSON-encoded string of the arguments.
     * IMPORTANT: this is a STRING, not an object. You must JSON.parse() it.
     * The LLM sometimes streams this in chunks — parse only when complete.
     */
    arguments: string;
  };
}

// ---------------------------------------------------------------------------
// SECTION 3: MESSAGES
// The conversation history that grows with each turn of the ReAct loop.
// ---------------------------------------------------------------------------

/**
 * A message from the end user.
 */
export interface UserMessage {
  role: "user";
  content: string;
}

/**
 * A message generated by the LLM.
 *
 * An assistant message can contain:
 *   - Just text (regular reply, no tool calls)
 *   - Just tool_calls (the LLM wants to use tools before replying)
 *   - Both (rare — usually means the LLM is "thinking aloud" then acting)
 */
export interface AssistantMessage {
  role: "assistant";
  /** The LLM's text reply, if it chose to write one. */
  content: string | null;
  /** Tool invocations requested by the LLM, if any. */
  tool_calls?: ToolCall[];
}

/**
 * The result of executing a tool — sent back to the LLM as a "tool" role message.
 *
 * The LLM reads this result and either:
 *   a) Calls more tools (keeps the loop going), or
 *   b) Writes a final answer to the user (ends the loop).
 */
export interface ToolResultMessage {
  role: "tool";
  /** Must match the tool_call_id from the ToolCall that triggered this result. */
  tool_call_id: string;
  /** The tool's output, serialized to a string. JSON.stringify complex objects. */
  content: string;
}

/** Union of all message types that can appear in conversation history. */
export type Message = UserMessage | AssistantMessage | ToolResultMessage;

// ---------------------------------------------------------------------------
// SECTION 4: AGENT CONFIG
// Runtime configuration for the reasoning loop.
// ---------------------------------------------------------------------------

/**
 * Configuration passed to the ReAct reasoning loop.
 */
export interface AgentConfig {
  /** Mistral model to use. "mistral-small-latest" recommended for reliable tool calling. */
  model: string;

  /**
   * System prompt: sets the agent's persona, goals, and constraints.
   * This is the most powerful lever for shaping agent behavior.
   *
   * @example
   * "You are a helpful assistant with access to tools. Use them to answer
   *  user questions accurately. Think step-by-step before calling a tool.
   *  When you have enough information, respond directly without calling more tools."
   */
  systemPrompt: string;

  /**
   * Safety limit on how many tool-call rounds before we force-stop.
   * Prevents infinite loops. Default: 10.
   */
  maxIterations?: number;

  /** Whether to print each step of the loop to stdout. Default: false. */
  verbose?: boolean;
}

// ---------------------------------------------------------------------------
// SECTION 5: AGENT RESULT
// What the loop returns when it finishes.
// ---------------------------------------------------------------------------

/**
 * The final output of a complete agent run.
 */
export interface AgentResult {
  /** The LLM's final text answer to the user. */
  answer: string;

  /** Every tool that was called during this run, in order. */
  toolCallsMade: Array<{
    toolName: string;
    arguments: Record<string, unknown>;
    result: string;
  }>;

  /** Total number of LLM API calls made (useful for cost estimation). */
  iterations: number;
}
